### ISSUE TITLE
What about jsonapi-serializer?

### ISSUE THREAD

**Issue by SeyZ** [danivek/json-api-serializer#14]
Hey!

I'm just wondering why you don't just fork https://github.com/SeyZ/jsonapi-serializer and submit PRs?

Cheers, :)

**Comment by danivek** [comment]
Hi @SeyZ,

Simply because default behaviours of jsonapi-serializer didn't fit to my need. I had to modify and pass serializer options each time I wanted to serialize a ressource (I wanted it to be reusable, customizable by schema). I also wanted support for populate/unpopulate relationships, etc...

All of these behaviours would have changed drastically how jsonapi-serializer works by default. And submitted PRs would have taken too much time. Because at that time, I needed a quick production ready library to be as flexible as i need, and I use it in so many api. So I made this library.

**Comment by recurrence** [comment]
Assuming this can be closed?
