### ISSUE TITLE
whitelist and blacklist rules on deserialize

### ISSUE THREAD

**Issue by hilaryosborne** [danivek/json-api-serializer#16]
Wondering if there are plans (or it is already implemented but im doing it wrong) for blacklist and whitelist rules to apply to deserialize. Currently it seems to be outputting a deserialized version of the data regardless of these rules. I am having to deserialize, serialize and then deserialize to get the clean data.

**Comment by danivek** [comment]
Your are right, currently blacklist or whitelist options are only effective on serialization. 
I think we can't apply these same options on deserialization. because attributes to remove or keep when serialize or deserialize can be different.

We need a blacklist and a whitelist options on deserializition too. I suggest to add these 2 options : 
- blacklistOnDeserialize
- whitelistOnDeserialize

Maybe you have a better idea for naming these options ?
