### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by karellm** [danivek/json-api-serializer#22]
Hi,

After getting tremendously frustrated at `jsonapi-serializer` I decided to try your library and so far so good. A real joy to use, very simple and yet it does what you expect it to. Anyway I wanted to make couple suggestions and see if there is interest:

- This [line](https://github.com/danivek/json-api-serializer/blob/master/lib/JSONAPISerializer.js#L433) would benefit from this [checking](https://github.com/danivek/json-api-serializer/blob/master/lib/JSONAPISerializer.js#L110). It would prevent this kind of crash:

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'limited' of undefined
    at Object.keys.forEach (/project/node_modules/json-api-serializer/lib/JSONAPISerializer.js:433:134)
```

- Casing usually is consistent throughout the project. What do you think of making `convertCase` and option of the `JSONAPISerializer` instance? That way no need to repeat myselft.

```
const Serializer = new JSONAPISerializer({
  convertCase: 'kebab-case',
  unconvertCase: 'caseCase'
});
```

I might have more things as I barely got started. I can make a PR if this is sounds like something you'd want.

**Comment by danivek** [comment]
Hi @karellm, 

Thanks for using `json-api-serializer`, I really appreciate you enjoy it.
Thanks for your feedback, I add a commit to prevent uncaught error for unregistered type or schema on relationships.

For the second point, you are right, it could be great to add global options on `JSONAPISerializer` instance to keep the code DRY. I had already anticipated this case as you can see on this [line](https://github.com/danivek/json-api-serializer/blob/master/lib/JSONAPISerializer.js#L24), but never implemented it yet.

a PR is welcome, otherwise I will make one. Tell me.

Thanks.

**Comment by karellm** [comment]
@danivek If you have the bandwidth to do it, they you will likely be 10 times faster than I poking around in a new codebase :) That said I understand if you don't and happily will tackle it. Let me know!

**Comment by karellm** [comment]
Thanks @danivek. Can you release a new version?

**Comment by danivek** [comment]
version 1.7.0 is out.

Thanks @karellm for your feedback
