### ISSUE TITLE
behavior when data is null or empty

### ISSUE THREAD

**Issue by jamesdixon** [danivek/json-api-serializer#53]
Hi,

While upgrading my project with `json-api-serializer`, I noticed a few tests failing when testing that an endpoint returns no data. For example, if someone requests a list of `campaign`s and there is no data, I'm seeing the following response:

```js
{ 
 jsonapi: undefined,
  meta: undefined,
  links: undefined,
  data: [],
  included: undefined 
}
```

The `data` portion is JSONAPI-compliant, but not sure about the rest. I actually have `jsonapiObject` set to `false` and I have no `meta`, `links` or `included`. Here's my registration:

```js
Serializer.register('campaign', {
    jsonapiObject: false,
    blacklist: ['batchId'],
    relationships: {
        business: { type: 'business', alternativeKey: 'businessId' }
    }
});
```
I'm not seeing anything in the spec that points to these attributes being `undefined` if they don't exist. I think the only place that may make sense is, for example, if you have a relationship that's empty, you might have `data: null`. Otherwise, it seems extraneous and adds up to unneeded bytes being sent across the network.

Thoughts?

Btw, I'm running 1.12.0.

**Comment by jamesdixon** [comment]
Actually, it looks like all of the `undefined` attributes are present even when there is `data`.

**Comment by jamesdixon** [comment]
UPDATE: 

I'm not seeing these `undefined` attrs when hitting my API via Insomnia, CURL, etc. It turns out that the object my framework returns during testing is prior to the response being serialized. My guess is that these attributes are present, but when running `JSON.stringify` any `undefined` attributes will be removed automatically.

All that said, it's going to change my tests a bit, but wanted to bring it up as it might be behavior that should change in the future to avoid any unforeseen issues.

Would love your thoughts on this @danivek.

Cheers!

**Comment by danivek** [comment]
Hi @jamesdixon, 

Interesting question !

The JSON:API specification deals with the JSON format **while** `json-api-serializer` deals/responds with Javascript Object. These 2 formats makes the difference about `undefined` values.

When serializing a Javascript Object to JSON with `JSON.stringify`, all `undefined` values are omitted, this is why you don't have `undefined` values when hitting your API API via Insomnia, CURL, etc... 
I recommend to use `JSON.stringify` for every response returning by the server (it's the default for most of http frameworks), since it produces a valid JSON-string and this response should be compliant with the spec because it's in JSON format.

In Javascript, there is no difference between `undefined` values and values NOT present, except for `hasOwnProperty` test:
```Javascript
var object = { attr1: undefined };
typeof object.attr1 // "undefined"
typeof object.attr2 //  "undefined"
object.hasOwnProperty("attr1") // true
object.hasOwnProperty("attr2") // false
```

But `json-api-serializer` can remove these `undefined` values, to be closer with JSON format, to be 'more' spec compliant and to avoid confusion.

@mattii any thoughts about implementing it in `json-api-serializer` ?

**Comment by mattii** [comment]
I never encountered any problems with it because I also use `JSON.stringify` for tests. Since it's the standard way of preparing JSON-payloads for responses or requests, I don't see a need to add the handling of these values to this serializer again. But maybe we could add a *Caveat* section to the README to warn users about it and advice to use `JSON.stringify` if they encounter problems with the presence of `undefined` properties?

**Comment by jamesdixon** [comment]
@danivek @mattii thanks for the explanation. It confirms my findings. In practice, it's not a big deal. It just so happens that my testing framework for Hapi.js returns the response before serialization, hence while the `undefined` values are there.
