### ISSUE TITLE
Any way to support computed attributes?

### ISSUE THREAD

**Issue by saygun** [danivek/json-api-serializer#66]
Hello

Is there any way to mask attribute with function thus computed attributes could be added on serializer level?

Thanx in advance.

**Comment by danivek** [comment]
No it's not possible actually.

Maybe we could had an option `transform` that takes a function to transform each data before the serialization.

**Comment by saygun** [comment]
Thank you for reply.

That's an good option. What about something like this, is it bad approach?

`serializers/user.js`
```
{
  ...,
  whitelist: ['name', 'profileImage'],
  get profileImage(data, extraData) {
    // compute something
  }
}
```
Serializer chould check itself for whitelist attributes just after not finding it in the data or vice versa.

**Comment by danivek** [comment]
I think this approach could have a better place on a `model` or a `class` before using serialization.

**Comment by johannesschobel** [comment]
I think, the most generic approach would be to have some kind of `Transformers`.. basically, a transformer is a class that transforms the input object (model) to another output structure.. This can be used to rename attributes (e.g., rename `givenName` to `firstName`) or add "computed attributes" (e.g, `name : firstname + ' ' + lastname`)

In the PHP world (i know) there is a "state-of-the-art" package for this purpose, that's called `fractal` ( https://fractal.thephpleague.com/ ).

Maybe you can take a look at the `Transformer` part?
I would really love to see such an approach in this package, because it is a highly versatile and flexible approach..

All the best

**Comment by danivek** [comment]
I think we should avoid introducing a new kind of domain-specific language (DSL) in this library. `json-api-serializer` is only responsible to (de)serialize a data to JSON API compliant responses. If you want to transform your data, you should do it before using this library.

The only possible option we could add for this library, is a `transform` option, that will act as a hook before (de)serializing attributes. So you will be able to use any kind of library you want to transform attributes.
